name: tourn
version: '0.1'
main: com.filikr.tourn.Tourn
api-version: '1.21'
load: STARTUP

commands:
  command: {}
#    description: Команды для работы с командами игроков
#    aliases:
#      - com


